export default {
  index: '概述',
  'data-types': '数据类型',
  'type-check': '类型判断',
  'array-methods': '数组方法',
  'string-methods': '字符串方法',
  'new-constructor': '构造函数与 new',
  'debounce-throttle': '防抖与节流',
  'closure': '闭包',
  'copy': '深拷贝与浅拷贝',
  'prototype': '原型与原型链',
  'this': 'this 指向',
  'context': '执行上下文',
  'event-loop': '事件循环',
  'promise': 'Promise 与 async/await',
  'event': '事件机制',
  'set-map': 'Set 与 Map',
  'gc': '垃圾回收',
  'float': '浮点精度',
  'spread': '展开运算符',
}
