export default {
  index: '概述',
  'two-sum': '两数之和',
  'move-zeroes': '移动零',
  'remove-duplicates': '删除有序数组重复项',
  'array-unique': '数组去重',
  'remove-element': '移除元素',
  'longest-increasing': '最长连续递增子序列',
  'chunk': '数组分块',
  'count-by': 'countBy 筛选',
  'valid-parentheses': '有效的括号',
  'min-remove-parentheses': '最小括号删除',
  'daily-temperatures': '每日温度',
  'queue-to-stack': '用队列实现栈',
  'circular-queue': '环形队列',
  'shuffle-array': '打乱有序数组',
  'fibonacci': '斐波那契数列',
  'unique-paths': '路径计数',
  'product-except-self': '除自身以外数组乘积',
}
