export default {
  index: '概述',
  reactivity: '响应式原理',
  template: '模板语法',
  lifecycle: '生命周期',
  setup: 'setup',
  'v-model': 'v-model 原理',
  communication: '组件通信',
  'keep-alive': 'keep-alive',
  nextTick: 'nextTick',
  slot: '插槽',
  watch: 'watch 与 watchEffect',
  computed: '计算属性',
  fragment: 'Fragment',
  performance: '性能优化',
  'h-function': 'h 函数',
  'global-properties': '全局属性',
  'router-guard': '路由守卫',
}
